### PR TITLE
[YNGJ-574] Background Kit - Set Background Size

### PR DESCRIPTION
**Pull request by Beznus**
#### Screens

Screen Shot 2022-03-22 at 2 19 18 PM

#### Breaking Changes

No, this adds a new feature to existing kit, does not change existing features.

#### Runway Ticket URL

[[YNGJ-574]](https://nitro.powerhrg.com/runway/backlog_items/YNGJ-574)

#### How to test this

Go to playbook kit docs and view the size, it should show the style that has been set with cover as default.

added automated tests

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [x] **SCREENSHOT** Please add a screen shot or two.
- [x] **SPECS** Please cover your changes with specs.
- [x] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

### CODE REVIEW

**Comment by thestephenmarshall** [comment]
@jasperfurniss @jasoncypret do we want to showcase all of the options or perhaps use an image for the examples here?

**Comment by jasoncypret** [comment]
If we show something here I'd made the example small. This only works when showing an image as a background.

**Comment by Beznus** [comment]
I will add an image to the example, should I use a specific image?

**Comment by Beznus** [comment]
Screen Shot 2022-02-21 at 3 49 32 PM

**Comment by Beznus** [comment]
@thestephenmarshall could you take another look and see what you think?

**Review by thestephenmarshall — APPROVED** [review]

**Pull request merged**
