### PR TITLE
Remove deprecated props

### PR DESCRIPTION
**Pull request by pauljpark**
#### Screens

[INSERT SCREENSHOT]
Screen Shot 2021-11-16 at 1 22 28 PM
Screen Shot 2021-11-16 at 1 21 05 PM
Screen Shot 2021-11-16 at 1 21 55 PM
Screen Shot 2021-11-16 at 1 22 08 PM

#### Breaking Changes

[Yes/No (Explain)]

[#### Runway Ticket URL](https://nitro.powerhrg.com/runway/backlog_items/PLAY-6)

[INSERT URL]

#### How to test this

[INSERT TESTING DETAILS]

#### Checklist:

- [ ] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **URGENCY** Please select a release milestone
- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [ ] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [ ] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

*The normal release cut off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

### CODE REVIEW

**Comment by jasoncypret** [comment]
@pauljpark updated your label. Deprecated is reserved for when we deprecate code. You only updated docs.

**Comment by jasoncypret** [comment]
@pauljpark you have merge conflicts

```sh
git checkout master
git pull
git checkout [yourbranch]
git merge origin/master
git push --force-with-lease
```

**Review by jasoncypret — APPROVED** [review]

**Comment by jasoncypret** [comment]
@pauljpark Whats the status here? Why no momevent?

**Comment by pauljpark** [comment]
> @pauljpark Whats the status here? Why no momevent?

@jasoncypret all set, sorry thought i resolved already

**Pull request merged**
