### PR TITLE
Add Props To React Doc Example Files for Dark Mode

### PR DESCRIPTION
**Pull request by ljtinney**
#### Breaking Changes

no

#### Runway Ticket URL

[NUXE-236](https://nitro.powerhrg.com/runway/backlog_items/NUXE-236)

#### How to test this

View the doc examples and ensure no errors occur and all examples are visible and working.

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **URGENCY** Please select a release milestone
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [x] **SCREENSHOT** Please add a screen shot or two.
- [x] **SPECS** Please cover your changes with specs.
- [x] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

*The normal release cut off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

### CODE REVIEW

**Review by jasoncypret — CHANGES_REQUESTED** [review]
This needs refreshing from Master to clean up the conflicts

**Comment by jasoncypret** [comment]
This is a HUGE PR! I'm gonna need some extra ಠ_ಠ on it. CC @thestephenmarshall @bh247484 @jasperfurniss @coleerikson

**Review by jasoncypret — CHANGES_REQUESTED** [review]
Since it looks like you are making everything consistent...it looks like we missed a few:

- [x] radio
- [ ] select
- [ ] selectable-card
- [ ] Selectable-icon
- [ ] Selectable-icon-card
- [ ] selectable-list
- [ ] text-input
- [ ] textarea
- [ ] typeahead
- [ ] highlight
- [ ] Icon Circle
- [ ] Icon Stat Value
- [ ] Icon Value
- [ ] Loading Inline
- [ ] Multiple Users
- [ ] Multiple Users Stacked
- [ ] Nav
- [ ] Popover
- [ ] RichTextEditor
- [ ] Source
- [ ] StarRating
- [ ] Stat Change
- [ ] Table
- [ ] Timeline
- [ ] Title
- [ ] Home Address Street
- [ ] LabelPill
- [ ] LabelValue
- [ ] Message
- [ ] Person
- [ ] PersonContact
- [ ] StatValue
- [ ] Timestamp
- [ ] Time Range Inline
- [ ] Title Count
- [ ] TitleDetail
- [ ] WeekdayStacked
- [ ] User



image

image


ect...

**Comment by ljtinney** [comment]
Yup, I'm haven't gotten to all of the kit examples yet. Still working through them.

**Review by jasoncypret — APPROVED** [review]

**Review by thestephenmarshall — APPROVED** [review]

**Pull request merged**
