### PR TITLE
NUX-1286 - Update dark props for Textarea kit

### PR DESCRIPTION
**Pull request by coleerikson**
#### Screens
**Rails**
textarea-dark-rails

**React**
textarea-dark-react

#### Runway Ticket URL
[https://nitro.powerhrg.com/runway/backlog_items/NUX-1286](https://nitro.powerhrg.com/runway/backlog_items/NUX-1286)

#### Checklist:
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review
- [x] **SCREENSHOT** Please add a screen shot or two
- [x] **SPECS** Please cover your changes with specs
- [x] **CHANGELOG** Please add an entry on `[Unreleased]` section to every functionality `ADDED`/`CHANGED`/`DEPRECATED`/`REMOVED`/`FIXED`

### CODE REVIEW

**Comment by kellyeryan** [comment]
Hi Cole, I think it's still missing validation on the React side and also a few methods that go along with validation:

      prop :validation, type: Playbook::Props::Hash,
                        default: {}
      prop :value


      def classname
        generate_classname("pb_text_input_kit", dark_class) + error_class
      end


      def validation_message
        validation[:message] || ""
      end


      def validation_pattern
        validation[:pattern] || nil
      end

**Comment by coleerikson** [comment]
Yup I'm looking at that now.

**Comment by coleerikson** [comment]
@thestephenmarshall squashed and merged conflict resolved. 👍

**Comment by thestephenmarshall** [comment]
Thanks @coleerikson

**Pull request merged**
