### PR TITLE
[PLAY-731] Adding optional vertical borders to Table kit

### PR DESCRIPTION
**Pull request by carloslimasd**
**What does this PR do?**
Add optional vertical (right and left) cell borders to the Table kit, so that I can apply full cell borders to Tables when I want/need to.

[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-731)

**Screenshots:**
image

**How to test?** Steps to confirm the desired behavior:
1. Go to Table kit on Playbook
2. Scroll down until the Vertical Borders section

#### Checklist:
- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **DEPLOY** I have added the `milano` label to show I'm ready for a review.
- [ ] **TESTS** I have added test coverage to my code.

### CODE REVIEW

**Comment by jasoncypret** [comment]
Looks good but I did find this weird border hover bug when resized small. https://share.getcloudapp.com/2Nubo90b

**Review by jasoncypret — APPROVED** [review]

**Comment by carloslimasd** [comment]
> Looks good but I did find this weird border hover bug when resized small. https://share.getcloudapp.com/2Nubo90b

Working on it! Thanks @jasoncypret

**Comment by carloslimasd** [comment]
It's fixed. Can you take another look, @jasoncypret?

**Review by nidaqg — APPROVED** [review]
🚀

**Review by jasoncypret — APPROVED** [review]

**Pull request merged**
