### PR TITLE
Automated CHANGELOG generation

### PR DESCRIPTION
**Pull request by drborges**
#### Runway Ticket URL

This PR proposes using [Github-Changelog-Generator](https://github.com/github-changelog-generator/Github-Changelog-Generator) to automate the `CHANGELOG.md` generation.

Manually generating changelog files is tedious and error-prone. The proposed solution is fairly flexible and relies on [Changelog](https://keepachangelog.com/en/1.0.0) good practices driven by Github labels on PRs, release tags and milestones.

Here're a few interesting features:

- It can reuse existing changelogs, only appending changes to the file since a given release tag.
- It allows PR's and Issues to be categorized between `bug`, `enhancements`, and `breaking` via Github `labels`:
Screen Shot 2020-02-18 at 12 09 32 PM
Screen Shot 2020-02-18 at 12 07 50 PM
- It will automatically add any merged PR under the merged PRs section in case it did not fall into the `bug` nor `enhancement` sections, meaning every PR shipped will show up in the changelog automatically.
- It can highlight PRs containing breaking changes based on the Github label `breaking`.
- It allows configuring custom labels.

Here's a sneak peek on what the final generated changelog looks like:

changelog

# The CLI

In my tests, I've use a global installation of the gem, here's the command I used to generate the changelog on the screenshot above:

```sh
github_changelog_generator -u powerhome -p playbook --token a38fac1d5e1af2716433bd52dcadfaf04efa0d09 --base CHANGELOG.md --since-tag 4.2.0
```

#### How it would work (ideally)

The changelog generation would be handled by CI, likely happening as part of the release process when the GH tag is created, right before publishing gems and NPM packages to the registries. With this, no human would have to manually generate changelogs.

This solution might require some coordination with @powerhome/guardians-of-the-galaxy.

#### Breaking Changes

Changes the changelog generation process from manual to automated based on Github labels. To keep the changelog consistent and organized, PR authors would have to start tagging their PRs properly with `bug`, `enhancement` and `breaking`.

#### Checklist:

- [ ] **SPECS** Please cover your changes with specs
- [ ] **CHANGELOG** Please add an entry on `[Unreleased]` section to every functionality `ADDED`/`CHANGED`/`DEPRECATED`/`REMOVED`/`FIXED`

### CODE REVIEW

**Comment by thestephenmarshall** [comment]
I think this would be great! I marked this for future release bc we will have to create some docs on how to properly tag, etc. Perhaps we would want to target 5.0.0 for this change. Overall, this will benefit everyone with regards to workflow and hopefully avoid those nasty conflicts in CHANGELOG.md.

**Comment by drborges** [comment]
@powerhome/ux-team just to clarify, I don't think this PR is yet shippable. It would be nice if some of you could play around with the solution to see what works and what doesn't so we can try to fine-tune the automation before disrupting your current workflow.

**Comment by drborges** [comment]
@powerhome/ux-team I've added some more info about how the CLI works, and what the full automated process could look like. Let me know what you think.

cc @powerhome/nitro-architects

**Comment by wadewinningham** [comment]
LGTM - In my experience with the GraphQL changelog, you just want to review it and not forget it as it could use some cleanup from time to time depending on how you update it and if it could get screwed up due to merge conflicts.

**Comment by drborges** [comment]
[semantic-release](https://github.com/semantic-release/semantic-release) could be a potential alternative for generating changelogs off of commit messages following certain Github supported conventions.

**Pull request closed without merging**
