### PR TITLE
Drop support for node v8.9.4

### LINKED ISSUE #475: Node version 8.9.4 does not work
Package.json file says node version can be `"node": "8.9.4 || 10.17.0",` but v8.9.4 errors with:

```
➜  playbook git:(master) yarn
yarn install v1.13.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error eslint@6.6.0: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1". Got "8.9.4"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

`v10.17.0` works just fine.

### PR DESCRIPTION
**Pull request by rafbgarcia**
Closes #475 

To be merged after powerhome/nitro-web#13414 is merged.

### CODE REVIEW

**Comment by rafbgarcia** [comment]
I'm going to wait on https://github.com/powerhome/nitro-web/pull/13414 before merging this one.

**Comment by thestephenmarshall** [comment]
I think this might need to be rebased on the branch that addresses CI failure.

**Comment by rafbgarcia** [comment]
Understood. Do you plan to merge it now or just when nitro-sg PR is merged?

**Comment by thestephenmarshall** [comment]
Probably once the `nitro-sg` PR is merged. Could we add a reference to that PR here too?

**Comment by rafbgarcia** [comment]
done

**Comment by thestephenmarshall** [comment]
Depends on https://github.com/powerhome/nitro-web/pull/13414

**Comment by rafbgarcia** [comment]
I'm closing this for now since that PR in Nitro had to be reverted.

**Pull request closed without merging**
