### PR TITLE
[CMPN-16] Allow all HTML options on input in PbCheckbox Rails kit

### PR DESCRIPTION
**Pull request by stephenmckeon**
#### Screens
Screen Shot 2020-09-10 at 4 18 58 PM
Screen Shot 2020-09-10 at 4 20 22 PM

#### Breaking Changes

No. This PR adds the `input_options` prop to the checkbox kit so PlayBook users can pass every single kind of HTML element option to the input element. This PR does not remove any props as to not break any existing usages of the checkbox kit.

Read [this](https://github.com/powerhome/rfcs/blob/master/0052-playbook-html-attribute-standards.md) RFC for more details.

#### Runway Ticket URL

https://nitro.powerhrg.com/runway/backlog_items/CMPN-16

#### How to test this

[INSERT TESTING DETAILS]

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `depreciation`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [x] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.

### CODE REVIEW

**Review by garettarrowood — APPROVED** [review]
Looks good to me!

**Review by thestephenmarshall — APPROVED** [review]
Looks good to me. @jasoncypret thoughts?

**Comment by jasoncypret** [comment]
Will this work in the form kit? Has that been tested?

**Comment by garettarrowood** [comment]
I don't see a reason why this wouldn't work in the form kit. Perhaps this PR could pass the `input_options` into one of the `checkbox` input in one of the form doc examples (and leave it there for future discovery by developers) to verify this works?

**Comment by stephenmckeon** [comment]
@jasoncypret @garettarrowood `input_options` as a prop in the form kit doesn't work, but checkbox already accepts options within the form kit:

Screen Shot 2020-09-14 at 9 48 56 AM

I added the options to the form docs in Playbook as well.

**Review by thestephenmarshall — CHANGES_REQUESTED** [review]
Please add spec coverage to continue.

**Review by thestephenmarshall — APPROVED** [review]

**Pull request merged**
