### PR TITLE
[PLAY-186] Use Auto in Images Transitions

### PR DESCRIPTION
**Pull request by Ivancandido11**
React Kit Coverage
#### Screens

Could not upload the video in this PR but I uploaded it in the runway story.

#### Breaking Changes

No

#### Runway Ticket URL

[Play-186](https://nitro.powerhrg.com/runway/backlog_items/PLAY-186)

#### How to test this

In dev tools click the network tab and there will be a `Disable cache` checkbox. When checked images will not be cached and the transitions will work as normal, also the class `ls-is-cached` will not appear on the `img` element. When unchecked images will be checked and the images will immediately appear without the transitions, also the class `ls-is-cached` will appear on the `img` element.

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [ ] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [ ] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

### CODE REVIEW

**Review by thestephenmarshall — CHANGES_REQUESTED** [review]
@Ivancandido11 I'm looking at the PR env and it appears as though the animations are not working as they should be according to what I see at https://playbook.powerapp.cloud/kits/image/react

Everything seems to be losing frames or skipping the animations all together.

**Comment by Ivancandido11** [comment]
@thestephenmarshall Don't we want the images to immediately show if they are cached? Im confused on what we are trying to achieve.

**Comment by thestephenmarshall** [comment]
Pending alpha testing https://github.com/powerhome/nitro-web/pull/25815

**Comment by jasperfurniss** [comment]
Closing this until we can revisit the story on our board for reviewing.

**Pull request closed without merging**
