### PR TITLE
[NUXE-332] Input Margin Update

### PR DESCRIPTION
**Pull request by stephenmckeon**
#### Breaking Changes

No. The default `margin small` was removed from the `text_input_wrapper`, but added to the `pb_caption_kit` (by default). Visually, any existing implementations of the text input kit will remain the same. 

#### Runway Ticket URL

https://nitro.powerhrg.com/runway/backlog_items/NUXE-332

#### How to test this

The text input kit should have a small margin on the bottom by default. When a user specifies either `margin-bottom` or `margin` prop, the default `margin-bottom` is overridden.

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **URGENCY** Please select a release milestone
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [x] **SCREENSHOT** Please add a screen shot or two.
- [x] **SPECS** Please cover your changes with specs.
- [x] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

*The normal release cut off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

### CODE REVIEW

**Comment by bh247484** [comment]
Just noticed some odd behavior on the form group kit.  Do a one to one with the [Milano Deploy](https://pr1236.playbook.beta.hq.powerapp.cloud/kits/form_group/react) and [production](https://playbook.powerapp.cloud/kits/form_group/react).  The 'button' and 'select' examples are misaligned.

**Comment by bh247484** [comment]
Margin bottom select sass overrides in Nitro:
[Spot 1](https://github.com/powerhome/nitro-web/blob/master/components/email/app/assets/stylesheets/email/email_campaigns/email_campaigns.scss#L202-L206), [Spot 2](https://github.com/powerhome/nitro-web/blob/master/components/installation_scheduler/app/components/InstallScheduleApp/NavBar/styles.scss#L18-L22), [Spot 3](https://github.com/powerhome/nitro-web/blob/master/components/installation_scheduler/app/components/InstallScheduleApp/ScheduleFilter/styles.scss#L4-L8), [Spot4](https://github.com/powerhome/nitro-web/blob/master/components/nitro_component_transition/app/components/LeadSafetyDetailsApp/LeadSafetyDetailsForm/styles.scss#L2-L7).

**Comment by bh247484** [comment]
Sorry those ^ were selects.  Leaving them there though in case we take on the select kit's bottom margin as well.

Here are text-input overrides in Nitro:
[Spot 1](https://github.com/powerhome/nitro-web/blob/master/components/home_tour/app/assets/stylesheets/home_tour/overrides.scss#L57), [Spot 2](https://github.com/powerhome/nitro-web/blob/master/components/connect-web-ui/vendor/Playbook/components/TextInput.scss#L37-L39), [Spot 3](https://github.com/powerhome/nitro-web/blob/master/components/nitro_component_transition/app/assets/stylesheets/accessory_items/form.scss#L33-L35), [Spot 4](https://github.com/powerhome/nitro-web/blob/master/components/email/app/assets/stylesheets/email/email_campaigns/email_campaigns.scss#L240-L242), [Spot 5](https://github.com/powerhome/nitro-web/blob/master/components/nitro_component_transition/app/assets/stylesheets/accessory_items/index.scss#L19-L21), [Spot 6](https://github.com/powerhome/nitro-web/blob/master/components/nitro_component_transition/app/assets/stylesheets/nitro_component_transition/accessory_questions.scss#L19-L21), [Spot 7](https://github.com/powerhome/nitro-web/blob/master/components/nitro_component_transition/app/assets/stylesheets/projects/roofing_calculator_form.scss#L1-L2), [Spot 8](https://github.com/powerhome/nitro-web/blob/master/components/solar_roofing/app/assets/stylesheets/solar_roofing/project_portal/_all.scss#L81-L83).

Those were for a quick search for `.text_input_wrapper` and `pb_text_input_kit` + `*.scss`.  Also fwiw some of those are single style overrides that may affect an entire swath of Nitro.  For example looks like Spot 1 affects all of Home Tour.

**Comment by jasoncypret** [comment]
I just noticed date-picker is not working correctly now. I think we need more time on this one CC: @coleerikson

**Comment by kre8sions** [comment]
Closing pr but keep branch alive @jasoncypret

**Pull request closed without merging**
