### PR TITLE
Title count react kit

### PR DESCRIPTION
**Pull request by kellyeryan**
#### Github Issue

#233

#### Screens

Screen Shot 2020-06-01 at 12 10 19 PM

Screen Shot 2020-06-01 at 12 10 27 PM

#### Breaking Changes

No breaking changes

#### Checklist:

- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review
- [X] **SCREENSHOT** Please add a screen shot or two
- [x] **SPECS** Please cover your changes with specs - NA
- [x] **CHANGELOG** Please add an entry on `[Unreleased]` section to every functionality `ADDED`/`CHANGED`/`DEPRECATED`/`REMOVED`/`FIXED`

### CODE REVIEW

**Comment by garettarrowood** [comment]
@jasoncypret - Every time a new base branch is specified in Playbook it makes recovering from this scenario pretty difficult. These types of changes should not be merge conflicts. The author of this PR had similar problems last week [and wrote about them here](https://github.com/powerhome/playbook/pull/798#issuecomment-633598738). Is there a workflow in which Playbook can maintain `master` as its base branch? That would 1. Remove merge conflicts in this scenario, and if there were a legitimate conflict - 2. Make resolving it simply standard rebasing procedure.  cc/ @thestephenmarshall @xjunior @benlangfeld

**Comment by thestephenmarshall** [comment]
@garettarrowood I don't see a selected Milestone for this one. Is this something that we want to get into this release today?

**Comment by garettarrowood** [comment]
@thestephenmarshall - Whatever you think! Is there a protocol for adding milestones? I've not added one myself before.

**Comment by thestephenmarshall** [comment]
@garettarrowood we have been using Milestones to help determine which release cycle each PR attempting to target. It is a little duplicative tbh considering the branch name provides that information already. I do want to consider [your suggestion here](https://github.com/powerhome/playbook/pull/825#issuecomment-637003016) to update our branch naming strategies. I have also found that simple works better for the same reasons outline within [Github Flow](https://githubflow.github.io).

**Comment by garettarrowood** [comment]
@thestephenmarshall - Thank you for that link! I was not aware of the naming around these work flows. Very informative!

**Pull request merged**
