### PR TITLE
[CMPN-17] Add input options to Radio Kit

### PR DESCRIPTION
**Pull request by ljtinney**
#### Screens

92961052-9e57f100-f43c-11ea-9642-41d8e30dff20

92961056-9ef08780-f43c-11ea-8bd3-5b32f493d9d9

#### Breaking Changes

No.
This PR adds the options prop to the radio kit so PlayBook users can pass every single kind of HTML element option to the input element.
This PR does not remove any props as to not break any existing usages of the radio kit.

#### Runway Ticket URL

https://nitro.powerhrg.com/runway/backlog_items/CMPN-17

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `depreciation`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [x] **SCREENSHOT** Please add a screen shot or two.
- [x] **SPECS** Please cover your changes with specs.

*The normal release cut off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

### CODE REVIEW

**Review by garettarrowood — APPROVED** [review]

**Review by thestephenmarshall — CHANGES_REQUESTED** [review]
On the milano env, I am noticing an error being thrown [here](https://pr1099.playbook.beta.gm.powerapp.cloud/kits/radio/rails)

**Comment by garettarrowood** [comment]
Attempting a label cycle to see if this was a deployment issue.

**Comment by garettarrowood** [comment]
It was not a deployment issue :( . We will take a look at what happened. Something appears to have happened in the transfer from #1089

**Comment by garettarrowood** [comment]
@thestephenmarshall - This is now working at https://pr1099.playbook.beta.hq.powerapp.cloud/kits/radio/rails .

**Review by thestephenmarshall — APPROVED** [review]

**Review by thestephenmarshall — APPROVED** [review]

**Pull request merged**
