### PR TITLE
[NUXE-740] WIP - Rails cust icon

### PR DESCRIPTION
**Pull request by bh247484**
#### Screens

[INSERT SCREENSHOT]

#### Breaking Changes

[Yes/No (Explain)]

#### Runway Ticket URL

[INSERT URL]

#### How to test this

[INSERT TESTING DETAILS]

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **URGENCY** Please select a release milestone
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [ ] **SCREENSHOT** Please add a screen shot or two.
- [x] **SPECS** Please cover your changes with specs.
- [x] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

*The normal release cut off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

### CODE REVIEW

**Comment by jasoncypret** [comment]
Please add your runway title

**Comment by jasperfurniss** [comment]
I'm going to pull this down later this week and see if I can make the dev exp a little cleaner if possible.

**Comment by thestephenmarshall** [comment]
@jasperfurniss @jasoncypret I am re-creating this PR from `master` so this one will be superseded and closed FYI.

**Comment by thestephenmarshall** [comment]
Superseded by https://github.com/powerhome/playbook/pull/1582

**Pull request closed without merging**
