### PR TITLE
[NUXE-23] - Fix tooltip with CSS

### PR DESCRIPTION
**Pull request by coleerikson**
#### Screens
tooltip-top

tooltip-bottom

tooltip-left

tooltip-right

#### Breaking Changes

No - These are CSS updates.

#### Runway Ticket URL

https://nitro.powerhrg.com/runway/backlog_items/NUXE-23

#### How to test this

Hover

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **URGENCY** Please select a release milestone
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [x] **SCREENSHOT** Please add a screen shot or two.
- [x] **SPECS** Please cover your changes with specs.
- [x] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

*The normal release cut off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

### CODE REVIEW

**Comment by jasoncypret** [comment]
This looks good. Were you planning on improving the docs while you're in here? or a separate story? @coleerikson

**Comment by coleerikson** [comment]
@jasoncypret Exactly. I know you were looking to add a click option but that seems like another story. It shouldn't be hard to add. I wrote it up https://nitro.powerhrg.com/runway/backlog_items/NUXE-199

**Comment by kre8sions** [comment]
@coleerikson can we try to use spacing variables where possible

**Comment by coleerikson** [comment]
@kre8sions Added.

**Pull request merged**
