### PR TITLE
[PLAY-24]  Improve max width global props docs/visual-guidelines

### PR DESCRIPTION
**Pull request by jon1735**
#### Screens

Screen Shot 2021-11-17 at 10 58 22 AM

#### Breaking Changes

No breaking changes

#### Runway Ticket URL

https://nitro.powerhrg.com/runway/backlog_items/PLAY-24

#### How to test this
Go to: https://playbook.powerapp.cloud/visual_guidelines and make sure the max width example is there.

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [x] **SCREENSHOT** Please add a screen shot or two.
- [x] **SPECS** Please cover your changes with specs.
- [x] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

### CODE REVIEW

**Comment by jon1735** [comment]
I also converted the original slim file to an erb file.

**Comment by jasoncypret** [comment]
GREAT JOB!!!

Max Width Example

Some changes:

1. Added copy, titles, & captions
2. Reconfigure examples using the background kit instead and inside the props example section (Title 4 Dark Mode for text)
3. Make the card container a wider max-width to show the largest example. (it's ok to shrink for smaller screens)
4. Let's keep the props example simple. We don't need the full react setup. 


I made a quick example with some added copy and other improvements. This one is a bit different because we don't have tokens to display. You will need to add your visual example inside the same card. Note that I made the example a bit wider than the others on the page. This is so we can display the max-width example for the largest size.

**Comment by jon1735** [comment]
Screen Shot 2021-11-18 at 9 48 37 AM

**Comment by jon1735** [comment]
Screen Shot 2021-11-18 at 10 08 37 AM

**Comment by kre8sions** [comment]
@jon1735 Lets just use a separator instead of multiple cards he
Screen Shot 2021-11-18 at 2 31 56 PM
re

**Review by kre8sions — CHANGES_REQUESTED** [review]
see my previous comment

**Comment by jon1735** [comment]
Screen Shot 2021-11-18 at 3 45 30 PM

**Review by kre8sions — APPROVED** [review]

**Pull request merged**
