### PR TITLE
[PLAY-20] Add Line Height Tokens on Visual Guidelines

### PR DESCRIPTION
**Pull request by dmcindoe**
#### Screens

[INSERT SCREENSHOT]
Screenshot_11_17_21__2_49_PM
Screenshot_11_17_21__2_50_PM

#### Breaking Changes

[Yes/No (Explain)]

#### Runway Ticket URL

[INSERT URL]

#### How to test this

[INSERT TESTING DETAILS]

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [x] **SCREENSHOT** Please add a screen shot or two.
- [x] **SPECS** Please cover your changes with specs.
- [x] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

### CODE REVIEW

**Comment by jasoncypret** [comment]
I have some feedback but need to provide a design example to explain. Great start!

**Comment by jasoncypret** [comment]
Note the update to the runway story

**Comment by kre8sions** [comment]
@dmcindoe let make this example look more like this
Lineheight

**Comment by jasoncypret** [comment]
@kre8sions @dmcindoe One tweak I would make is that text size. Let's make it the size of a title 3. I'd like to be able to see 3 lines to compare.

image

**Comment by dmcindoe** [comment]
Hey I was able to get changes made however, I wanted to check. Did you want  the number of columns just wrap, or did you want to limit the number of columns to 3?

**Comment by dmcindoe** [comment]
Playbook_Design_System

**Comment by dmcindoe** [comment]
Playbook_Design_System-2

**Comment by dmcindoe** [comment]
Had issues pushing commits through. Per conversation with Gillian created a new pull request since that was an option. https://github.com/powerhome/playbook/pull/1663

**Pull request closed without merging**
