### PR TITLE
Add Matching Decimals Prop to Currency Kit 

### PR DESCRIPTION
**Pull request by stephenmckeon**
React Kit Coverage
This PR makes a new prop available to the currency kit: `decimals`. When this prop is passed the string `"matching"`,  the decimal styling will match the styling of the whole number that proceeds it. This feature is needed by Inifinty Inc as they receive many mocks that use the currency kit, but the mocks have styling that wasn't available. This will increase development speed going forward. 

## React 
Screen Shot 2022-06-29 at 9 36 25 AM

## Rails
Screen Shot 2022-06-29 at 9 36 39 AM

#### Breaking Changes

No; the new optional prop "decimals" for the currency kit will not cause any existing implementations of the currency kit to break. 

#### Runway Ticket URL

None.

#### How to test this

- Verify that the existing playbook Currency kit examples remain unchanged
- Spot check Currency kit implementations in the wild to make sure they are unchanged
- Use the Currency kit and pass the new prop "decimals" with the option "matching":  ensure that the decimals are the same font and size as the whole numbers

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [x] **SCREENSHOT** Please add a screen shot or two.
- [x] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

### CODE REVIEW

**Comment by stephenmckeon** [comment]
Not sure why the specs around the DatePicker kit are failing. Seems unrelated to my changes.

**Review by jasoncypret — COMMENTED** [review]
LGTM I know we will need to get some good Ninja testing in the spots that use currency kit heavily.

**Comment by thestephenmarshall** [comment]
Looking into the spec failure

**Review by thestephenmarshall — CHANGES_REQUESTED** [review]
@stephenmckeon Looks good, but could I have you update the spec tests please?

**Review by thestephenmarshall — APPROVED** [review]
Great job! 🚀

**Pull request merged**
