### PR TITLE
[Forms] Drop simple form support

### PR DESCRIPTION
**Pull request by xjunior**
#### Breaking Changes

Drops simple form support as it hasn't been used anywhere.

#### How to test this

Playbook documentation should have no mention of underlying form systems.

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **URGENCY** Please select a release milestone
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [x] **SCREENSHOT** Please add a screen shot or two.
- [x] **SPECS** Please cover your changes with specs.
- [x] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

*The normal release cut off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

### CODE REVIEW

**Comment by jasoncypret** [comment]
Where is this used in Nitro?

**Comment by xjunior** [comment]
@jasoncypret no where in nitro

**Comment by jasoncypret** [comment]
Note: this is currently being tested in Nitro with #1406

**Comment by jasoncypret** [comment]
Ninja tested and sealed!

**Review by jasoncypret — APPROVED** [review]

**Pull request merged**
