### PR TITLE
Move everything into 'playbook'

### PR DESCRIPTION
**Pull request by xjunior**
First step moving toward the organization proposed and accepted by [RFC 56](https://github.com/powerhome/rfcs/blob/master/0056-playbook-project-organization.md)

Next step is extracting `playbook-docs`.

### CODE REVIEW

**Comment by jasoncypret** [comment]
@xjunior great start! I think this should be it's own release given the number of files. I saw the WIP tag was removed, are you hoping to get this merged soon?

**Comment by xjunior** [comment]
@jasoncypret yes. I wanted to have you and the other UX Engineers eyes on this before we merge, but aside from the conflicts (which I plan to fix once I get y'all ok's) I'm ready to release this.

**Comment by jasoncypret** [comment]
@thestephenmarshall any concerns with DIST and include paths in Nitro?

**Comment by thestephenmarshall** [comment]
@jasoncypret I haven't been able to test this just yet. Likely there will be more changes needed to our rake task(s) and `webpack.config.js`.

**Review by thestephenmarshall — COMMENTED** [review]
Looks to be working so far, but can you please merge in `7.4.0`? It seems this is behind by 1 release and is missing some things such as the latest changes to `pb_release.rake` to support distribution.

**Comment by xjunior** [comment]
@thestephenmarshall thanks for checking! I was waiting for your feedback before rebasing and all. I'll update the base branch.

When are we thinking of switching to the regular `master` base branch approach?

**Comment by xjunior** [comment]
@thestephenmarshall good to go?

**Comment by thestephenmarshall** [comment]
@xjunior I think so, let me run a couple of tests locally then we can merge.

**Comment by thestephenmarshall** [comment]
@jasoncypret would we want to consider this as breaking? One upside would be ability to add the work that @maddiemc01 is on being it is also breaking.

**Review by thestephenmarshall — APPROVED** [review]
I tested running Playbook locally, generating a kit and finally creating a release and publishing. All working as expected.

**Review by jasoncypret — APPROVED** [review]

**Review by jasoncypret — CHANGES_REQUESTED** [review]
The only request I have is to move the current readme back to the root, or add a new one that links to the one inside the playbook folder.

**Comment by jasoncypret** [comment]
As far as breaking and considering this a major release. I don't feel like this is breaking for clients...only for kit contributors in terms of startup.

**Review by jasoncypret — APPROVED** [review]
We have some conflicts with the new kits that were created. As soon as these are resolved I'll get this in master and release 7.5.0

**Comment by xjunior** [comment]
@jasoncypret done, can you check if the merge was alright?

**Comment by jasoncypret** [comment]
@xjunior On it brother

**Pull request merged**
